name: weather_app
description: A Flutter weather app with Firebase authentication
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg